RocketEshop/Controllers/GenresController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RocketEshop.Core.Interfaces;
using RocketEshop.Core.Models;

namespace RocketEshop.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class GenresController : Controller
    {
        // Service
        private readonly IGenresService _service;

        public GenresController(IGenresService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Description")] Genre genre)
        {
            try
            {
                await _service.AddAsync(genre);
                TempData["success"] = "Genre added successfully!";
            }
            catch(Exception)
            {
                TempData["error"] = "There was an error.";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            return await GetGenreDetails(id);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id,Name,Description")] Genre genre)
        {
            try
            {
                await _service.UpdateAsync(genre);
                TempData["success"] = "Genre updated successfully!";
            }
            catch (Exception)
            {
                TempData["error"] = "There was an error.";
            }
            return RedirectToAction(nameof(Index));
            
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await GetGenreDetails(id);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Genre genre)
        {
            //try
            //{
                await _service.DeleteAsync(genre);
                TempData["success"] = "Genre deleted successfully!";
            //}
            //catch (Exception)
            //{
            //    TempData["error"] = "There was an error.";
            //}
            return RedirectToAction(nameof(Index));
            
        }

        private async Task<IActionResult> GetGenreDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Genre? genre = await _service.GetByIdAsync(id.Value);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }
    }
}

RocketEshop/Views/Genres/Create.cshtml
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization
@model RocketEshop.Core.Models.Genre;

@{
    ViewData["Title"] = Localizer["add.genre"];
}

<h2>@Localizer["add.genre"]</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-4">
                <label asp-for="Name" class="control-label">@Localizer["name"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group mb-4">
                <label asp-for="Description" class="control-label">@Localizer["description"]</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-4">
                <input type="submit" value=@Localizer["add"] class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Localizer["back.to.list"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RocketEshop/Views/Genres/Delete.cshtml
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization
@model RocketEshop.Core.Models.Genre

@{
    ViewData["Title"] = Localizer["delete.genre"];
}

<h2>@Localizer["delete.genre"]</h2>

<h3>@Localizer["delete.msg"]</h3>
<div>
    <hr />
    <dl class="row mb-4">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value=@Localizer["delete"] class="btn btn-danger" /> |
        <a asp-action="Index">@Localizer["back.to.list"]</a>
    </form>
</div>

RocketEshop/Views/Genres/Edit.cshtml
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization
@using RocketEshop.Core.Enums
@model RocketEshop.Core.Models.Genre

@{
    ViewData["Title"] = Localizer["edit"];
}

<h2>@Localizer["edit"]</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">@Localizer["name"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">@Localizer["description"]</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value=@Localizer["save"] class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@Localizer["back.to.list"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RocketEshop/Views/Genres/Index.cshtml
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization
@model IEnumerable<RocketEshop.Core.Models.Genre>
@{
    ViewData["Title"] = Localizer["genre.list"];
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Localizer["genre.list"]</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Genres" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-square"></i> &nbsp; @Localizer["add.new.genre"]
            </a>
        </div>
    </div>
</div>
<br />
<table class="table tale-bordered table-striped" style="width:100%">
    <thead>
        <tr class="table-primary">
            <th>
                @Localizer["genre"]
            </th>
            <th>
                @Localizer["description"]
            </th>
            <th style="width: 3rem"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>
                    @obj.Name
                </td>
                <td>
                    @obj.Description
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">

                        <a asp-controller="Genres" asp-action="Edit" asp-route-id="@obj.Id"
                           class="btn btn-primary mx-2"><i class="bi bi-pencil"></i>@Localizer["edit"]</a>
                        <a asp-controller="Genres" asp-action="Delete" asp-route-id="@obj.Id"
                           class="btn btn-danger mx-2"><i class="bi bi-trash"></i>@Localizer["delete"]</a>

                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>