RocketEshop/Controllers/BrowseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RocketEshop.Core.Domain;
using RocketEshop.Core.Interfaces;
using RocketEshop.Infrastructure.Data.ViewModel;

namespace RocketEshop.Controllers
{
    [AllowAnonymous]
    public class BrowseController : Controller
    {
        private readonly IGamesService _gamesService;
        private static Filters Filters;

        public BrowseController(IGamesService service)
        {
            this._gamesService = service;
            Filters ??= new Filters();
        }

        public async Task<IActionResult> Index()
        {
            return View(new BrowseVM(_gamesService.FetchFilteredGamesList(Filters), Filters));
        }

        [HttpPost]
        [ActionName("Search")]
        public async Task<IActionResult> Index([Bind("QuickSearchFilter,Availability,Sorting,MinPrice,MaxPrice")] Filters filtersVm)
        {
            Filters = filtersVm;
            return RedirectToAction(nameof(Index));
        }
    }
}

RocketEshop/Controllers/GamesController.cs
using System.Globalization;
using System.Text.Json.Nodes;
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.WebUtilities;
using RocketEshop.Core.Interfaces;
using RocketEshop.Core.Models;
using RocketEshop.Infrastructure.Data.ViewModel;

namespace RocketEshop.Controllers
{
    [Authorize("AdminOnly")]
    public class GamesController : Controller
    {
        // Service
        private readonly IGamesService _gamesService;
        private readonly IGenresService _genresService;
        
        private readonly RequestLocalizationOptions localizationOptions;

        private static List<GameCSVRecordVM> gamesFromCSV;

        public GamesController(IGamesService service, IGenresService genresService, RequestLocalizationOptions localizationOptions)
        {
            _gamesService = service;
            _genresService = genresService;
            this.localizationOptions = localizationOptions;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _gamesService.GetAllAsync());
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            Game? game = await GetGameDetails(id);
            if (game == null)
            {
                return NotFound();
            }
            GameVM gameVm = new GameVM(game);
            return View(gameVm);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            TempData["genreOptions"] = await GetGameOptions();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title,Description,Price,ImageUrl,Quantity,ReleaseDate,Rating,Genres")] GameCreateUpdateVM gameVm)
        {
            try
            {
                Game game = await gameEntityFromGameCreateRequestDto(gameVm);
                await _gamesService.AddAsync(game);
                TempData["success"] = "Game added successfully!";
            }
            catch(Exception)
            {
                TempData["error"] = "There was an error.";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            Game? game = await GetGameDetails(id);
            if(game == null)
            {
                return NotFound();
            }
            GameCreateUpdateVM gameVm = new GameCreateUpdateVM(game);
            TempData["genreOptions"] = await GetGameOptions();
            return View(gameVm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind("Id,Title,Description,Price,ImageUrl,Quantity,ReleaseDate,Rating,Genres")] GameCreateUpdateVM gameVm)
        {
            try
            {
                Game game = await gameEntityFromUpdateGameVm(gameVm);
                await _gamesService.UpdateAsync(game);
                TempData["success"] = "Game updated successfully!";
            }
            catch (Exception e)
            {

                TempData["error"] = e.Message;
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            Game? game = await GetGameDetails(id);
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Game game)
        {
            await _gamesService.DeleteAsync(game);
            TempData["success"] = "GameViewModel deleted successfully!";
            return RedirectToAction(nameof(Index));
            
        }

        // CSV IMPORT
        
        [HttpGet]
        public IActionResult CsvInsert(List<GameCSVRecordVM>? games = null)
        {
            if (games == null)
            {
                games = new List<GameCSVRecordVM>();
            }
            return View(games);
        }

        [HttpPost]
        public IActionResult CsvInsert(IFormFile file, [FromServices] Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            string fileName = $"{hostingEnvironment.WebRootPath}\\uploads\\{file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();
            }

            try
            {
                gamesFromCSV = this.GetGamesList(file.FileName);
            }
            catch(Exception e)
            {
                TempData["error"] = e.Message;
            }
            return View(gamesFromCSV);
        }

        [HttpPost]
        public IActionResult CsvInsertConfirm()
        {
            List<Game> gameEntities = new List<Game>();
            Dictionary<string, Genre> genres = new Dictionary<string, Genre>();
            foreach (GameCSVRecordVM gameCsvRecordVm in gamesFromCSV)
            {
                Game game = new Game();
                game.Title = gameCsvRecordVm.Title;
                game.Description = gameCsvRecordVm.Description;
                game.ReleaseDate = gameCsvRecordVm.ReleaseDate.ToDateTime(new TimeOnly(0, 0));
                game.ImageUrl = gameCsvRecordVm.ImageUrl;
                game.Price = gameCsvRecordVm.Price;
                game.Quantity = gameCsvRecordVm.Quantity;
                game.Rating = gameCsvRecordVm.Rating;

                game.GameGenreLink = new List<GameGenre>();
                foreach (string genreName in gameCsvRecordVm.Genres)
                {
                    if (!genres.ContainsKey(genreName))
                    {
                        Genre? genre = _genresService.FetchGenreByName(genreName);
                        if (genre == null)
                        {
                            genre = new Genre();
                            genre.Name = genreName;
                        }
                        genres.Add(genreName, genre);
                    }
                    GameGenre gameGenre = new GameGenre();
                    gameGenre.Game = game;
                    gameGenre.Genre = genres[genreName];
                    game.GameGenreLink.Add(gameGenre);
                }

                gameEntities.Add(game);
            }
            
            _gamesService.BulkUploadGames(gameEntities);
            return RedirectToAction(nameof(Index));
        }

        // PRIVATE - UTILS

        private async Task<Game?> GetGameDetails(int? id)
        {
            if (id == null)
            {
                return null;
            }
            return await _gamesService.GetByIdAsync(id.Value);
        }

        private async Task<SelectList> GetGameOptions()
        {
            IEnumerable<Genre> genres = await _genresService.GetAllAsync();
            return new SelectList(genres, "Id", "Name");
        }

        private async Task<Game> gameEntityFromUpdateGameVm(GameCreateUpdateVM gameVm)
        {
            Game game = new Game();
            game.Id = gameVm.Id ?? throw new Exception("A game with no Id was given");
            game.Title = gameVm.Title;
            game.Price = gameVm.Price;
            game.ImageUrl = gameVm.ImageUrl;
            game.Quantity = gameVm.Quantity;
            game.Rating = gameVm.Rating;
            game.ReleaseDate = gameVm.ReleaseDate;
            game.Description = gameVm.Description;

            game.GameGenreLink = new List<GameGenre>();
            foreach (int genreId in gameVm.Genres)
            {
                Genre? genre = await _genresService.GetByIdAsync(genreId) ?? throw new Exception("cannot find genre with id " + genreId);
                
                GameGenre gameGenre = new GameGenre();
                gameGenre.Game = game;
                gameGenre.Genre = genre;

                game.GameGenreLink.Add(gameGenre);
            }
            return game;
        }

        private async Task<Game> gameEntityFromGameCreateRequestDto(GameCreateUpdateVM gameVm)
        {
            Game game = new Game();
            game.Title = gameVm.Title;
            game.Price = gameVm.Price;
            game.ImageUrl = gameVm.ImageUrl;
            game.Quantity = gameVm.Quantity;
            game.Rating = gameVm.Rating;
            game.ReleaseDate = gameVm.ReleaseDate;
            game.Description = gameVm.Description;

            game.GameGenreLink = new List<GameGenre>();
            foreach (int genreId in gameVm.Genres)
            {
                Genre? genre = await _genresService.GetByIdAsync(genreId) ?? throw new Exception("cannot find genre with id " + genreId);

                GameGenre gameGenre = new GameGenre();
                gameGenre.Game = game;
                gameGenre.Genre = genre;

                game.GameGenreLink.Add(gameGenre);
            }
            return game;
        }

        private List<GameCSVRecordVM> GetGamesList(string fileName)
        {
            List<GameCSVRecordVM> games = new List<GameCSVRecordVM>();
            var path = $"{Directory.GetCurrentDirectory()}{@"\wwwroot\uploads"}" + "\\" + fileName;
            using (var reader = new StreamReader(path))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Read();
                csv.ReadHeader();
                csv.Context.RegisterClassMap<GameCSVRecordVMMap>();

                string[] headers = { "Title", "Price", "ImageUrl", "Quantity", "Rating", "ReleaseDate", "Description", "Genres" };
                string[]? csvHeaders = csv.HeaderRecord;
                if (csvHeaders == null)
                {
                    throw new Exception("The CAV file must contain headers");
                }

RocketEshop/Controllers/OrdersController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RocketEshop.Core.Interfaces;

namespace RocketEshop.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IGamesService _gamesService;
        private readonly IApplicationUserService _applicationUserService;
        private readonly IOrdersService _ordersService;

        public OrdersController(IGamesService gamesService, IApplicationUserService applicationUserService, IOrdersService ordersService)
        {
            _gamesService = gamesService;
            _applicationUserService = applicationUserService;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(orders);
        }
    }
}       

RocketEshop/Controllers/ShoppingCartController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RocketEshop.Core.Interfaces;
using RocketEshop.Infrastructure.Data.ViewModel;

namespace RocketEshop.Controllers;

    [Authorize]
    public class ShoppingCartController: Controller
    {
        private readonly IGamesService _gamesService;
        private readonly IApplicationUserService _applicationUserService;
        private readonly IOrdersService _ordersService;

        public ShoppingCartController(IGamesService gamesService, IApplicationUserService applicationUserService, IOrdersService ordersService)
        {
            _gamesService = gamesService;
            _applicationUserService = applicationUserService;
            _ordersService = ordersService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            string userId = GetUserId();
            
            var items = _applicationUserService.GetUserShoppingCart(userId);
            decimal total = _applicationUserService.GetShoppingCartTotal(userId);
            
            var response = new ShoppingCartVM(items, total);

            return View(response);
        }
    
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            string userId = GetUserId();

            var item = await _gamesService.GetByIdAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            if(item.Quantity <= 0)
            {
                TempData["error"] = "There is no more items";
                return RedirectToAction(nameof(Index));
            }
            _applicationUserService.AddItemToUserCart(item, userId);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            string userId = GetUserId();

            var item = await _gamesService.GetByIdAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            _applicationUserService.RemoveItemFromUserCart(item, userId);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            string userId = GetUserId();
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            var items = _applicationUserService.GetUserShoppingCart(userId);
            if (items.Count == 0)
            {
                return View("EmptyCart");
            }
            else
            {
                await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
                _applicationUserService.ClearUserShoppingCart(userId);            
                return View("OrderCompleted");
            }
        }

        // PRIVATE - UTILS

        private string GetUserId()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return userId;
        }

    }

RocketEshop/Views/Shared/_Identity.cshtml
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Mvc.Localization
@using RocketEshop.Core.Enums
@inject UserManager<ApplicationUser> UserManager;

@if(!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> @Localizer["login"]
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> @Localizer["register"]
    </a>
}
else{
    <div class="nav-item dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge"></i> @Localizer["hello"] @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn" style="z-index: 999999">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i>@Localizer["orders"]
                </a>
            </li>
            <li>
                <a class="dropdown-item" asp-controller="ShoppingCart" asp-action="Index">
                    <i class="bi bi-cart4"></i>@Localizer["cart"]
                </a>
            </li>
            @if (User.IsInRole(UserRole.ADMIN.ToString()))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> @Localizer["users"]
                    </a>
                </li>
            }
        </ul>
    </div>

    <span style="padding: 5px;"></span>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn -btn-ouline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> @Localizer["logout"]
        </button>
    </form>
}

RocketEshop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using RocketEshop.Core.Enums
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RocketEshop</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @*for bootstrap theme*@
    <link rel="stylesheet" href="~/css/bootstrapTheme.css"/>
    @*for toast popup*@
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/RocketEshop.styles.css" asp-append-version="true" />
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body class="my-gradient">
<header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-default my-bg-1" style="border: none;">
        <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/brand-logo.png" width="50%" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                </ul>
                <button type="button" class="btn btn-outline-info mx-4" data-bs-toggle="tooltip" data-bs-title="@Localizer["change.language.tooltip"]" onclick="changeLanguage()">
                    <img src="~/@Localizer["flag"]" alt="lang_flag" height="16"/>
                </button>
                <a>
                    @await Component.InvokeAsync("ShoppingCartIcon")
                </a>
                <partial name="_Identity.cshtml" />
            </div>
        </div>
    </nav>
    </header>
    @*second navbar - don't put in header or sticky-top won't work*@
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark my-bg" style="border:none;">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item" style="padding-left:30px;padding-right:30px;">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                           <b>@Localizer["home"]</b>
                        </a>
                    </li>
                    <li class="nav-item" style="padding-left:30px;padding-right:30px;">
                        <a class="nav-link" asp-area="" asp-controller="Browse" asp-action="Index">
                            <b>@Localizer["browse"]</b>
                        </a>
                    </li>
                    <li class="nav-item" style="padding-left:30px;padding-right:30px;">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">
                            <b>@Localizer["about.us"]</b>
                        </a>
                    </li>
                    <li class="nav-item" style="padding-left:30px;padding-right:30px;">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">
                            <b>@Localizer["contact.us"]</b>
                        </a>
                    @if (User.Identity.IsAuthenticated && User.IsInRole(UserRole.ADMIN.ToString()))
                    {
                        <li class="nav-item dropdown" style="padding-left:30px;padding-right:30px;">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><b>@Localizer["cms"]</b></a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Games" asp-action="Index">@Localizer["games"]</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Genres" asp-action="Index">@Localizer["genre"]</a>
                                    <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Games" asp-action="CsvInsert">@Localizer["csv.insert"]</a>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
<br />
<div class="container mb-5">
    <main role="main" class="pb-3">
        @*to show toast popup*@
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>
<br /><br /><br />
    <footer class="border-top footer text-muted">
        <div class="d-lg-flex justify-content-between">
            <div>
                <span><img src="~/brand-logo.png" width="40%"/></span>
            </div>
            <div class="copyright">
                <p>developed and maintained by <a href="https://github.com/cgeopapa/RocketEshop">Team Rocket</a></p>
            </div>
            <div>
                <ul class="d-flex gap-3 list-unstyled">
                    <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                    <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                    <li><a href="#"><i class="bi bi-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@*for bootstrap5 bundle*@
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="js/tooltip.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RocketEshop/Views/Shared/_Notification.cshtml
@*if successfully completed, show appropriate toast popup*@
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@*if there was an error, show appropriate toast popup*@
@if (TempData["error"] != null)
{
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}